name: MarkBind Action

on:
  push:
    branches:
      - main

jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Deploy MarkBind site
        uses: tlylt/markbind-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}